<?php

/**
 * Vite Manifest Helper Plugin
 *
 * This plugin provides helper functions for integrating Vite-built assets into Kirby.
 * It dynamically adapts its behavior based on the Kirby `debug` option:
 *
 * - In **development mode** (`debug` is true): It loads assets directly from the
 *   Vite development server, enabling Hot Module Replacement (HMR) for a fast
 *   development workflow.
 * - In **production mode** (`debug` is false): It reads the `manifest.json` file
 *   generated by Vite's build process to correctly reference hashed asset URLs,
 *   ensuring optimized and cache-busted production deployments.
 *
 * This plugin is essential for both development and production environments to
 * correctly serve and manage front-end assets.
 */

/**
 * Retrieves the Vite manifest file content.
 * The manifest is loaded once per path and cached for subsequent calls.
 *
 * @return array The decoded content of the manifest.json file, or an empty array if not found.
 */
function getViteManifest() {
    static $manifests = [];

    $manifestPath = kirby()->root('assets') . '/bundle/.vite/manifest.json';

    if (!array_key_exists($manifestPath, $manifests)) {
        $manifest = [];

        if (file_exists($manifestPath)) {
            $decoded = json_decode((string)file_get_contents($manifestPath), true);
            if (is_array($decoded)) {
                $manifest = $decoded;
            }
        }

        $manifests[$manifestPath] = $manifest;
    }

    return $manifests[$manifestPath];
}

/**
 * Generates the full URL for a Vite asset based on its entry name in the manifest.
 *
 * @param string $entry The entry name of the asset (e.g., 'js/index.js').
 * @return string|null The full URL to the asset, or null if the entry is not found.
 */
function getViteAssetUrl($entry) {
    $manifest = getViteManifest();
    
    if (isset($manifest[$entry]['file'])) {
        return url('assets/bundle/' . $manifest[$entry]['file']);
    }
    
    return null;
}

/**
 * Whether a manifest chunk belongs to the WebGL experience: it is the
 * vendor-three chunk, lives under js/three/, or statically imports (directly
 * or transitively) a chunk that does.
 *
 * @param string $key The manifest key of the chunk.
 * @param array $seen Keys already visited (guards against import cycles).
 * @return bool
 */
function isViteThreeChunk($key, array $seen = []) {
    $manifest = getViteManifest();
    $chunk = $manifest[$key] ?? null;

    if ($chunk === null || in_array($key, $seen, true)) {
        return false;
    }

    if (($chunk['name'] ?? '') === 'vendor-three' || str_starts_with($chunk['src'] ?? '', 'js/three/')) {
        return true;
    }

    $seen[] = $key;
    foreach ($chunk['imports'] ?? [] as $import) {
        if (isViteThreeChunk($import, $seen)) {
            return true;
        }
    }

    return false;
}

/**
 * Retrieves the URLs of dynamic imports associated with a given Vite entry.
 * These are assets that are loaded on demand by the main entry.
 *
 * Three.js and the worlds are only reachable through a dynamic import, and
 * only pages rendering a #webgl canvas run it, so their chunks are left out
 * unless $webgl is true. On a WebGL page only the experience's own file
 * (runExperience) and the page's own world chunk are returned: vendor-three
 * (651 KB) is left out so it doesn't compete with the render-critical CSS and
 * fonts in <head>; the dynamic import fetches it as soon as the script runs.
 *
 * @param string $entry The entry name (e.g., 'js/index.js').
 * @param bool $webgl Whether the page renders a #webgl canvas.
 * @param string|null $world Folder of the page's world chunk
 *                           (js/three/projects/<folder>/index.mjs); null preloads no world.
 * @return array An array of URLs for the dynamic imports.
 */
function getViteDynamicImports($entry, $webgl = false, $world = null) {
    $manifest = getViteManifest();
    $keys = [];

    foreach ($manifest[$entry]['dynamicImports'] ?? [] as $import) {
        if (!isViteThreeChunk($import)) {
            $keys[] = $import;
        } elseif ($webgl) {
            $keys[] = $import;

            if ($world !== null) {
                $worldKey = 'js/three/projects/' . $world . '/index.mjs';
                if (in_array($worldKey, $manifest[$import]['dynamicImports'] ?? [], true)) {
                    $keys[] = $worldKey;
                }
            }
        }
    }

    $imports = [];
    foreach (array_unique($keys) as $key) {
        if (isset($manifest[$key]['file'])) {
            $imports[] = url('assets/bundle/' . $manifest[$key]['file']);
        }
    }

    return $imports;
}

/**
 * Generates HTML <link rel="modulepreload"> tags for dynamic imports of a Vite entry.
 * This helps browsers preload modules for faster loading.
 *
 * @param string $entry The entry name (e.g., 'js/index.js').
 * @param bool $webgl Whether the page renders a #webgl canvas.
 * @param string|null $world Folder of the page's world chunk.
 * @return string HTML string containing modulepreload links.
 */
function vitePreloadLinks($entry, $webgl = false, $world = null) {
    $dynamicImports = getViteDynamicImports($entry, $webgl, $world);
    $html = '';
    
    foreach ($dynamicImports as $importUrl) {
        $html .= '<link rel="modulepreload" href="' . $importUrl . '">' . "\n";
    }
    
    return $html;
}

/**
 * Main Vite helper function to load assets.
 * In development mode, it loads assets from the Vite dev server with HMR client.
 * In production mode, it loads bundled assets from the manifest.
 *
 * @param string $entry The entry name of the asset (e.g., 'dev/js/index.js' for development, 'js/index.js' for production).
 * @param bool $webgl Whether the page renders a #webgl canvas (Page::rendersWebgl());
 *                    only then are the Three.js chunks modulepreloaded.
 * @param string|null $world Folder of the page's world chunk (Page::webglWorldChunk()).
 * @return string HTML string containing the script tags for the Vite assets.
 */
function vite($entry, $webgl = false, $world = null) {
    $html = '';
    if (option('debug')) {
        // In development, load from Vite dev server
        $viteServer = option('vite.server', 'http://localhost:9001'); // Use 9001 as default for consistency
        $html .= '<script type="module" src="' . $viteServer . '/@vite/client"></script>' . "\n";
        
        // Strip 'dev/' prefix for Vite dev server to match Vite's root configuration
        $devEntry = preg_replace('/^dev\//', '', $entry);
        $html .= '<script type="module" src="' . $viteServer . '/' . $devEntry . '"></script>' . "\n";
    } else {
        // In production, load from manifest
        $manifest = getViteManifest();
        if (isset($manifest[$entry])) {
            $html .= vitePreloadLinks($entry, $webgl, $world);
            $html .= '<script type="module" src="' . getViteAssetUrl($entry) . '"></script>' . "\n";
        }
    }
    return $html;
}

// Register Kirby helper functions
Kirby::plugin('studioisphording/vite-manifest', [
    'options' => [
        'cache' => true
    ],
    'helpers' => [
        'vite' => 'vite' // Reference the named function
    ]
]);
